pipeline {
    agent any

    triggers {
        pollSCM('H/5 * * * *')
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh './gradlew clean assemble'
            }
        }
        stage('Run') {
            steps {
                echo 'Running..'
                sh './gradlew run'
            }
        }
        stage('Run Task') {
            steps {
                echo 'Running..'
                sh './gradlew tasks runExecuteJarFromFileZip'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh './gradlew test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}